app/urls.py
from django.urls import path
from .views.user import UserCreateView, ProfileUpdateView, LoginView, LogoutView, AccountView, AccountDeleteView, AccountPasswordView
from .views.course import CourseView, CourseDetailView
from .views.project import ProjectListView, ProjectDetailView, ProjectStartView, ProjectAdminView,  CreateCommentView, ProjectUpdateView, ProjectDeleteView, TopPageView

app_name = "app"

urlpatterns = [
    path('', TopPageView.as_view(), name='top'),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('course/', CourseView.as_view(), name='courselist'),
    path('course/<int:pk>', CourseDetailView.as_view(), name="course"),
    path('project/', ProjectListView.as_view(), name='projectlist'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name="project"),
    path('readyfor/', ProjectStartView.as_view(), name='readyfor'),
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('account/delete/<int:pk>', AccountDeleteView.as_view(), name='accountDelete'),
    path('account/password/<int:pk>', AccountPasswordView.as_view(), name='accountPassword'),
    path('project-dashboard/', ProjectAdminView.as_view(), name='projectadmin'),
    path('comment/', CreateCommentView.as_view(), name="comment"),
    path('project-dashboard/<int:pk>/edit', ProjectUpdateView.as_view(), name='projectEdit'),
    path('project-dashboard/<int:pk>/delete', ProjectDeleteView.as_view(), name='projectDelete'),
]

chat/urls.py
from django.urls import path
from .views import CreateRoomView, ChatRoomDetailView, MessageCreateView 

app_name = "chat"

urlpatterns = [
    path('', CreateRoomView.as_view(), name='room'),
    path('room/<uuid:pk>/', ChatRoomDetailView.as_view(), name='chat-room'),
    path('chat/', MessageCreateView.as_view(), name='chat'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from common.error_log import server_error_display
import debug_toolbar

handler500 = server_error_display

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

app/views/project.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Comment, Plan
from django.urls import reverse, reverse_lazy
from ..forms import ProjectCreateForm, CommentForm, ProjectUpdateForm
from chat.forms import CreateRoomForm
from django.contrib import messages
from django.views.generic import TemplateView

class TopPageView(TemplateView):
    template_name = "top.html"

class ProjectListView(ListView):
    template_name = 'projects/projectList.html'
    model = Plan
    ordering = ['-created_at']

    def get_queryset(self):
        qs = Plan.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
            qs = qs.filter(title__contains=keyword)

        return qs

# プロジェクト詳細ページ
class ProjectDetailView(DetailView):
    template_name = 'projects/projectDetail.html'
    model = Plan

    # コメント投稿時のプロジェクトの指定
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['CommentForm'] = CommentForm(initial={'post': self.object})
        return context

    # ルーム作成時の実装
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['CreateRoomForm'] = CreateRoomForm(initial={'plan': self.object})
        return context

class ProjectStartView(LoginRequiredMixin, CreateView):
    form_class = ProjectCreateForm
    template_name = 'projects/project.html'
    model = Plan
    success_url = reverse_lazy('app:projectlist')

    def post(self, request, *args, **kwargs):
        user = request.user
        data = request.POST.dict()
        data['userPlan'] = user.id
        form = ProjectCreateForm(data=data, files=request.FILES)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "プロジェクトを作成しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "プロジェクトを作成できませんでした")
        return super().form_invalid(form)

# プロジェクト管理
class ProjectAdminView(ListView):
    template_name = 'projects/project-admin.html'
    model = Plan

# ユーザーのプロジェクトダッシュボード表示
class ProjectAdminView(TemplateView):
    template_name = "projects/project-admin.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if self.request.user.is_authenticated:
            context['projects_list'] = Plan.objects.filter(userPlan=self.request.user)
        else:
            context['projects_list'] = None

        return context

# プロジェクトの編集
class ProjectUpdateView(UpdateView):
    template_name = 'projects/projectUpdate.html'
    model = Plan
    form_class = ProjectUpdateForm
    success_url = reverse_lazy('app:projectadmin')

# プロジェクトの削除
class ProjectDeleteView(DeleteView):
    template_name = 'projects/projectDelete.html'
    model = Plan
    success_url = reverse_lazy("app:projectadmin")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "プロジェクトを削除しました")
        return super().delete(request, *args, **kwargs)

# コメント投稿
class CreateCommentView(CreateView):
    form_class = CommentForm
    template_name = 'projects/projectDetail.html'
    model = Comment
    success_url = reverse_lazy('app:projectlist')

    # プロジェクトの指定
    def comment_create(request):
        # どの投稿かのフィールドを指定
        post_id = request.POST.get("post")
        text = request.POST.get("text")
        data = {"text": text, "post": post_id}
        form = CommentForm(data=data)

        if form.is_valid():
            form.save()
            messages.success(request, "コメントを投稿しました")
        else:
            messages.error(request, "コメントが投稿できませんでした")

        return redirect("project")

    # ユーザーの指定
    def post(self, request, *args, **kwargs):
        user = request.user
        data = request.POST.dict()
        data['userComment'] = user.id
        form = CommentForm(data=data)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_url_success(self):
        return reverse_lazy("app:project",kwargs={"pk":self.kwargs["pk"]})

templates/projects/project-admin.html
<!-- form-base.htmlを使用する -->
{% extends "form_base.html" %}

{% block content %}
    <h3 class="mt-4 border-bottom">ダッシュボード一覧</h3>
    <a href="{% url 'app:readyfor' %}" class="btn btn-primary btn-sm my-3">プロジェクトを追加する</a>
    <table class="table table-striped table-bordered">
      {% for plan in projects_list %}
      <thead>
        <tr>
          <th scope="col">プロジェクト名</th>
          <th scope="row">{{ plan.title }}</th>
          <td>
            <a href="{% url 'app:projectEdit' plan.id %}" class="btn btn-outline-primary btn-sm">編集する</a>
            <a href="{% url 'app:projectDelete' plan.id %}" class="btn btn-outline-danger btn-sm">削除する</a>
          </td>
        </tr>
      </thead>
      {% endfor %}
    </table>
    <a href="{% url 'app:top'%}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/projects/project.html
{% extends "form_base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h3 class="mt-4 mb-5">開発プロジェクト作成</h3>
    <p class="mt-4 mb-5 border-bottom">
      <a href="https://broadleaf-baroness-77d.notion.site/c53a15b12a5e44709cc713f4f3e2d0fe">プロジェクトの作成方法</a>
    </p>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <input type="submit" value="プロジェクトを作成する" class="btn btn-primary">
        </div>
      </div>
    </form>
    <a href="{% url 'app:top' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/projects/projectDelete.html
<form action="" method="POST">{% csrf_token %}
    <input type="submit" value="削除します" class="btn btn-primary">
</form>

templates/projects/projectDetail.html
{% load bootstrap4 %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Developeer - チーム開発のマッチングサービス</title>

  <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/starter-template/">

  <!-- Bootstrap core CSS -->
  <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
  <link rel="stylesheet" href="{% static 'css/detail_page.css' %}">
  </head>
<body>
    
<div class="col-lg-8 mx-auto p-3 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <!-- プロジェクト名を表示 -->
    <h4 class="fs-4">{{plan.title}}</h4>
  </header>

  <main>
    <!-- 開発内容の表示 -->
    <p class="create-date">作成日 {{ plan.created_at }}</p>
    <h4 class="dev-content">開発内容：<br>{{plan.content}}</br></h4>
    <h4 class="dev-content">技術スタック：{{plan.language_category}}</h4>
    <h4>使用するリポジトリ：{{plan.repository_url}}</h4>
    <p class="fs-5 col-md-8 dev-flow">
      チーム開発までの流れ
      <p>1. プロジェクト作成者にチャットかコメントから、参加のメッセージを送ってください</p>
      <p>2. 開発内容・開発の期間・リポジトリの共有を確認します</p>
      <p>3. 開発中のコミュニケーションはチャットルームか<a href="https://discord.com/" target="_blank" rel="noopener noreferrer" class="back-project">discord</a>をご利用ください</p>
    </p>

    <!-- チャットルームへの遷移 -->
    {% if plan.chatroom %}
    <a href="{% url 'chat:chat-room' plan.chatroom.room_id %}">
      <button class="btn btn-primary">メッセージを送る</button>
    </a>
    {% else %}
    <form action="{% url 'chat:room' %}" method="POST">{% csrf_token %}
      {{ CreateRoomForm }}
      <input type="submit" class="btn btn-primary" value="メッセージを送る">
    </form>
    {% endif %}

    <hr class="col-3 col-md-2">
    <p>チーム開発のフローについて知りたい方はガイドを参照してください。
      <a href="https://ye-kou-xian-ren.gitbook.io/gitgithubdebuchmu/" target="_blank" rel="noopener noreferrer" class="back-project">Git/GitHub開発フローを見る</a>
    </p>
    
    <div class="row g-5">
      <a href="{% url 'app:projectlist' %}" rel="noopener" class="back-project">←プロジェクト一覧に戻る</a>
    </div>
  </main>
</div>
</body>
</html>

templates/projects/projectList.html
{% extends 'base.html' %}
{% block main %}
{% load imagekit %}
{% load static %}

{% if messages %}
  <div class="messages_ul">
    {% for message in messages %}
      <p class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert">{{ message }}</p>
    {% endfor %}
  </div>
{% endif %}

<main>
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">
        開発プロジェクト一覧
      </h1>
      <p class="lead text-muted">各言語・フレームワークを使った、チーム開発のプロジェクトがあります。チーム開発のプロジェクトに参加してみましょう。自分で始めることも可能です。</p>
      <a href="{% url 'app:readyfor' %}" class="btn btn-primary my-2">プロジェクトをはじめる</a>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 page-hide">
    {% for item in object_list %}
      <div class="col card-group">
          <div class="card shadow-sm">
            {% if item.img %}
              <img src="{{ item.img_thumbnail.url }}" class="bd-placeholder-img card-img-top" role="img">
            {% else %}
              <img src="https://i.gyazo.com/10b3a30413c180c3e6448f44e42344d6.png" class="bd-placeholder-img card-img-top" role="img">
            {% endif %}
            <div class="card-body">
              {% if item.userPlan.img %}
              <img src="{{ item.userPlan.img.url }}" class="user-icon">
              {% else %}
              <img src="https://i.gyazo.com/5bf4a87af591851f14b7b5ad2fd647e5.png" class="user-icon">
              {% endif %}
              <p class="card-text">{{ item.title }}</p>
              <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'app:project' item.pk %}">
                  <button type="button" class="btn btn-primary">
                    詳しく見る
                  </button>
                </a>
              </div>
            </div>
          </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
</main>
{% endblock main %}

templates/projects/projectUpdate.html
{% extends "form_base.html" %}
{% load bootstrap4 %}

{% block content %}
  <h3 class="mt-4 mb-5">開発プロジェクト編集</h3>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
      <div class="offset-md-3 col-md-9">
        <input type="submit" value="プロジェクトを更新する" class="btn btn-primary">
      </div>
    </div>
  </form>
  <a href="{% url 'app:top'%}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}