app/urls.py
from django.urls import path
from .views.user import UserCreateView, ProfileUpdateView, LoginView, LogoutView, AccountView, AccountDeleteView, AccountPasswordView
from .views.course import CourseView, CourseDetailView
from .views.project import ProjectListView, ProjectDetailView, ProjectStartView, ProjectAdminView,  CreateCommentView, ProjectUpdateView, ProjectDeleteView, TopPageView

app_name = "app"

urlpatterns = [
    path('', TopPageView.as_view(), name='top'),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('course/', CourseView.as_view(), name='courselist'),
    path('course/<int:pk>', CourseDetailView.as_view(), name="course"),
    path('project/', ProjectListView.as_view(), name='projectlist'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name="project"),
    path('readyfor/', ProjectStartView.as_view(), name='readyfor'),
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('account/delete/<int:pk>', AccountDeleteView.as_view(), name='accountDelete'),
    path('account/password/<int:pk>', AccountPasswordView.as_view(), name='accountPassword'),
    path('project-dashboard/', ProjectAdminView.as_view(), name='projectadmin'),
    path('comment/', CreateCommentView.as_view(), name="comment"),
    path('project-dashboard/<int:pk>/edit', ProjectUpdateView.as_view(), name='projectEdit'),
    path('project-dashboard/<int:pk>/delete', ProjectDeleteView.as_view(), name='projectDelete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from common.error_log import server_error_display
import debug_toolbar

handler500 = server_error_display

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/accounts/account.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Developeer - チーム開発のマッチングサービス</title>
    <!-- icon image -->
    <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/features/">
    <!-- Bootstrap core CSS -->
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
<body>
 
<div class="container px-4 py-5" id="hanging-icons">
    <h2 class="pb-2 border-bottom">{{user.username}}</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="col d-flex align-items-start">
        <div>
          <h3>アカウントの削除</h3>
          <p>以下のボタンからアカウントの削除をすることができます。</p>
          <a href="{%url 'app:accountDelete' user.pk %}" class="btn btn-danger">
              削除する
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div>
          <h3>お問い合わせ</h3>
          <p>サービスに関して、ご不明点などがございましたら、以下のフォームからご記入ください。</p>
          <a href="https://forms.gle/M4STM1SuK35xeL5L8" class="btn btn-primary">
              記入する
          </a>
        </div>
      </div>
    </div>
    <a href="{% url 'app:top'%}" class="btn btn-secondary btn-sm">戻る</a>
  </div>
</body>
</html>

templates/accounts/accountDelete.html
<form action="" method="POST">{% csrf_token %}
    <div class="form-group row">
        <div class="offset-md-3 col-md-9">
        <input type="submit" value="削除します" class="btn btn-primary">
        </div>
    </div>
</form>

templates/accounts/login.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/sign_form.css' %}">
  <title>Developeer - チーム開発のマッチングサービス</title>
  <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
</head>
<div class="form-wrapper">
    <h1>ログイン</h1>
    <form action="" method="POST">
      <div calss="form-item">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-item">
            {{ field.label }}
            <br>
            {{ field }}
            <br>
        </div>
            {{ field.error }}
        {% endfor %}
        <br>
      </div>
      <div class="button-panel">
        <button class="btn-login" type="submit">ログインする</button>
      </div>
    </form>
    <div class="form-footer">
        <p><a href="{% url 'app:signup' %}">新規登録はこちらから</a></p>
    </div>
</div>

templates/accounts/profile.html
{% extends "form_base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h3 class="mt-4 mb-5 border-bottom">プロフィール編集</h3>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <input type="submit" value="保存する" class="btn btn-primary">
        </div>
      </div>
    </form>
    <a href="{% url 'app:top'%}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/accounts/signup.html
{% load static %}
<head>
    <title>Developeer - チーム開発のマッチングサービス</title>
    <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
    <link rel="stylesheet" href="{% static 'css/sign_form.css' %}">
</head>
<form class="form-wrapper" method="POST" action="">
<h1>新規登録</h1>
{% csrf_token%}
<div class="form-item">
    {{form.as_p}}
</div>
<div class="button-panel">
    <input class="btn-signup" type="submit" value="アカウントを作成する" />
</div>
<div class="form-footer">
    <p><a href="{% url 'app:login' %}">ログインの方はこちらから</a></p>
</div>
</form>