app/urls.py
from django.urls import path
from .views.user import UserCreateView, ProfileUpdateView, LoginView, LogoutView, AccountView, AccountDeleteView, AccountPasswordView
from .views.course import CourseView, CourseDetailView
from .views.project import ProjectListView, ProjectDetailView, ProjectStartView, ProjectAdminView,  CreateCommentView, ProjectUpdateView, ProjectDeleteView, TopPageView

app_name = "app"

urlpatterns = [
    path('', TopPageView.as_view(), name='top'),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('course/', CourseView.as_view(), name='courselist'),
    path('course/<int:pk>', CourseDetailView.as_view(), name="course"),
    path('project/', ProjectListView.as_view(), name='projectlist'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name="project"),
    path('readyfor/', ProjectStartView.as_view(), name='readyfor'),
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('account/delete/<int:pk>', AccountDeleteView.as_view(), name='accountDelete'),
    path('account/password/<int:pk>', AccountPasswordView.as_view(), name='accountPassword'),
    path('project-dashboard/', ProjectAdminView.as_view(), name='projectadmin'),
    path('comment/', CreateCommentView.as_view(), name="comment"),
    path('project-dashboard/<int:pk>/edit', ProjectUpdateView.as_view(), name='projectEdit'),
    path('project-dashboard/<int:pk>/delete', ProjectDeleteView.as_view(), name='projectDelete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from common.error_log import server_error_display
import debug_toolbar

handler500 = server_error_display

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/account.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Developeer - チーム開発のマッチングサービス</title>
    <!-- icon image -->
    <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/features/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
<body>
 
<div class="container px-4 py-5" id="hanging-icons">
    <h2 class="pb-2 border-bottom">{{user.username}}</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="col d-flex align-items-start">
        <div>
          <h3>パスワードの変更</h3>
          <p>パスワードの変更をすることができます。以下のボタンを押して新しいパスワードを入力してください。</p>
          <a href="#" class="btn btn-primary">
            変更する
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div>
          <h3>アカウントの削除</h3>
          <p>以下のボタンからアカウントの削除をすることができます。</p>
          <a href="#" class="btn btn-danger">
              削除する
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div>
          <h3>お問い合わせ</h3>
          <p>サービスに関して、ご不明点などがございましたら、以下のフォームからご記入ください。</p>
          <a href="https://forms.gle/M4STM1SuK35xeL5L8" class="btn btn-primary">
              記入する
          </a>
        </div>
      </div>
    </div>
    <a href="{% url 'top'%}" class="btn btn-secondary btn-sm">戻る</a>
  </div>
</body>
</html>

templates/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Developeer - チーム開発のマッチングサービス</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Favicons -->
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
<meta name="theme-color" content="#7952b3">

<!-- Google Analytics -->
{% if GOOGLE_ANALYTICS_TRACKING_ID %}
  {% include 'ga.html' %}
{% endif %}

<style>
.bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
}

@media (min-width: 768px) {
.bd-placeholder-img-lg {
    font-size: 3.5rem;
  }
}
</style>
</head>
<body>
  
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <strong>developeer</strong>
      </a>
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:projectlist' %}">開発プロジェクトをさがす
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:readyfor' %}">チーム開発をはじめる
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:courselist' %}">学習する
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
        </ul>
        <!-- 検索フォーム -->
        <form>
          <input name="q" value="{{ request.GET.q }}" type="search" eholder="Search" aria-label="Search" class="search-form" placeholder="プロジェクトを検索">
        </form>
        <form class="d-flex">
          {% if user.is_authenticated %}
          <div class="action">
            <div onclick="menuToggle();">
              {% if user.img %}
              <a href="{% url 'app:projectadmin' %}" class="btn btn-primary my-2 my-sm-0" >自分のプロジェクト</a>
              <img src="{{ user.img.url }}" class="user-icon">
              {% else %}
              <a href="{% url 'app:projectadmin' %}" class="btn btn-primary my-2 my-sm-0" >自分のプロジェクト</a>
              <img src="https://i.gyazo.com/5bf4a87af591851f14b7b5ad2fd647e5.png" class="user-icon">
              {% endif %}
            </div>
            <div class="menu">
              <h3>{{ user.username}}</h3>
              <ul>
                <li>
                  <a href="{% url 'app:profile' user.pk %}">プロフィール編集</a>
                </li>
                <li>
                  <a href="{% url 'app:account' %}">アカウント設定</a>
                </li>
                <li>
                  <a href="{% url 'app:logout' %}">ログアウト</a>
                <li>
                  <a href="https://forms.gle/M4STM1SuK35xeL5L8">お問い合わせ</a>
                </li>
              </ul>
            </div>
          </div>
          {% else %}
          <a href="{% url 'app:login' %}" class="btn btn-primary my-2 my-sm-0" >ログイン</a>
          <a href="{% url 'app:signup' %}" class="btn btn-primary my-2 my-sm-0" >新規登録</a>
          </form>
          <img src="https://i.gyazo.com/5bf4a87af591851f14b7b5ad2fd647e5.png" class="user-icon">
          {% endif %}
      </div>
    </div>
  </nav>
  {% if messages %}
  <div class="messages_ul">
    {% for message in messages %}
      <p class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert">{{ message }}</p>
    {% endfor %}
  </div>
  {% endif %}
</header>



{% block main %}
{% endblock main %}

<footer class="container py-5">
    <div class="row">
        <div class="col-6 col-md">
        <h5>developeerについて</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted footer-link" href="https://broadleaf-baroness-77d.notion.site/developeer-f35963e4bf764e5b93084d832af5a595">サービス概要</a></li>
            <li><a class="text-muted footer-link" href="https://broadleaf-baroness-77d.notion.site/f293fff3094f4e498e373cd0897ebccb">コース概要</a></li>
            <li><a class="text-muted footer-link" href="https://broadleaf-baroness-77d.notion.site/d17b8422c91a415a969d4a5dc84a2d83">利用方法</a></li>
            <li><a class="text-muted footer-link" href="https://forms.gle/M4STM1SuK35xeL5L8">お問い合わせ</a></li>
            <li><a class="text-muted footer-link" href="https://forms.gle/oGHCyfiztn13Fu7Z7">サービスのご感想</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
          <h5>私達について</h5>
          <ul class="list-unstyled text-small">
              <li><a class="text-muted footer-link" href="https://broadleaf-baroness-77d.notion.site/5c29767170964926823f81337d9be164">メンバー</a></li>
              <li><a class="text-muted footer-link" href="https://forms.gle/Ug7GpSze6eHB1nb37">開発に参加したい</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
        <h5>SNS</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted footer-link" href="https://twitter.com/m8YFiPZsq7cJrif">Twitter</a></li>
        </ul>
        </div>
    </div>
</footer>
</body>
</html>



<script>
  menuToggle = () => {
    const toggleMenu = document.querySelector(".menu");
    toggleMenu.classList.toggle("active");
  }
</script>

<style>

header {
    width: 100%;
    position: fixed; 
    top: 0;
    left: 0;
    z-index: 1;
}

.page-hide {
    z-index: 0;
}

.user-icon {
    height: 50px;
    width: 50px;
    object-fit: cover;
    border-radius: 50%;
    border: 1.5px solid #f5f5f5;
}
.col-lg-4 {
    padding-left: 150px;
}

.circle-title {
    padding-top: 10px;
}

.circle-text {
    margin-right: 80px;
}

.intro {
    margin-top: 100px;
    margin-bottom: 100px;
}

.intro-account {
    margin-top: 100px;
}

.circle-detail {
    text-decoration: none;
    transition: border-color 0.3s;
}

.circle-detail:hover {
    border-bottom: 1px dotted #8c8c8c;
}

/* Profile DropDown */
.action .menu {
  position: absolute;
  top: 120px;
  right: -10px;
  padding: 10px 20px;
  background: #f8f9fa;
  width: 200px;
  box-sizing: 0 5px 25px rgba(0, 0, 0, 0.1);
  border-radius: 15px;
  transition: 0.5s;
  visibility: hidden;
  opacity: 0;
}

.action .menu.active {
  top: 80px;
  visibility: visible;
  opacity: 1;
}
  
.action .menu::before {
  content: "";
  position: absolute;
  top: -5px;
  right: 28px;
  width: 20px;
  height: 20px;
  background: #f8f9fa;
  transform: rotate(45deg);
}

.action .menu h3 {
  width: 100%;
  text-align: center;
  font-size: 18px;
  padding: 20px 0;
  font-weight: 500;
  color: #555;
  line-height: 1.5em;
}

.action .menu h3 span {
  font-size: 14px;
  color: #cecece;
  font-weight: 300;
}

.action .menu ul li {
  list-style: none;
  padding: 16px 0;
  border-top: 1px solid rgba(0, 0, 0, 0.05);
  display: flex;
  align-items: center;
}

.action .menu ul li a {
  display: inline-block;
  text-decoration: none;
  color: #555;
  font-weight: 500;
  transition: 0.5s;
}

.action .menu ul li:hover a {
  color: #4169e1;
}

.footer-link {
  text-decoration: none;
}

.footer-link:hover {
  text-decoration: underline;
}

</style>

templates/courseDetail.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Developeer</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/starter-template/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
<body>
    
<div class="col-lg-8 mx-auto p-3 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <span class="fs-4">{{ course.title }}</span>
  </header>

  <main>
    <p class="fs-5 col-md-8">{{ course.description }}</p>
    <div class="mb-5">
      <a href="{{ course.content }}" class="btn btn-primary">学習する</a>
    </div>
    <hr class="col-3 col-md-2 mb-5">
    <a href="{% url 'courselist'%}" class="btn btn-secondary btn-sm">コース一覧へ</a>

  </main>

  <footer class="pt-5 my-5 text-muted border-top">
    Created by the developeer team &middot; &copy; 2022
  </footer>
</div>
</body>
</html>

<style>
.back-course {
    text-decoration: none;
}

.back-course:hover {
    text-decoration: underline;
}

.btn-sm {
  margin-top: 60px;
}
</style>

templates/form_base.html
<!-- project.html・profile.htmlで使用 -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Developeer - チーム開発のマッチングサービス</title>
    <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/ga.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-KXJZQW4D7X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KXJZQW4D7X');
</script>

templates/projectDetail.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Developeer - チーム開発のマッチングサービス</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
<meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
<body>
    
<div class="col-lg-8 mx-auto p-3 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <!-- プロジェクト名を表示 -->
    <span class="fs-4">{{plan.title}}</span>
  </header>

  <main>
    <!-- 開発内容の表示 -->
    <h4>開発内容：<br>{{plan.content}}</br></h4>
    <h4>技術スタック：{{plan.language_category}}</h4>
    <h4>こちらのリポジトリを使用します：{{plan.repository_url}}</h4>
    <p class="fs-5 col-md-8 dev-flow">
      チーム開発までの流れ
      <p>1. プロジェクト作成者にチャットかコメントから、参加のメッセージを送ってください</p>
      <p>2. 開発内容・開発の期間・リポジトリの共有を確認します</p>
      <p>3. 開発中のチャットは、本サービスの<a href="" target="_blank" class="chat-link">グループチャット</a>か<a href="https://discord.com/" target="_blank" class="chat-link">discord</a>をご利用ください</p>
    </p>

    <div class="mb-5">
      <a href="http://localhost:8000/chat/room/" class="btn btn-primary">開発に参加する</a>
    </div>

    <hr class="col-3 col-md-2 mb-5 ">

    <div class="row">
      <div class="col">
          <ul class="list-unstyled">
            {{ comment.text }}
          </ul>
      </div>
    </div>

    <div class="comment-form">
      <p>コメントからでも参加することができます</p>
      <form action="" method="POST">{% csrf_token %}
          {{ CommentForm }}
        <br><input type="submit" value="コメントする" class="btn btn-primary comment-form"></br>
      </form>
    </div>

    <div class="row g-5">
      <a href="{% url 'projectlist' %}" rel="noopener" class="back-project">«プロジェクト一覧に戻る</a>
    </div>
  </main>
</div>
</body>
</html>

<style>
.dev-flow {
  margin-top: 30px;
}

.back-project {
    text-decoration: none;
}

.chat-link {
  text-decoration: none;
}

.chat-link:hover {
  text-decoration: underline;
}

.back-project {
  margin-top: 100px;
}

.back-project:hover {
    text-decoration: underline;
}

.comment-form {
  margin-top: 10px;
}
</style>

templates/top.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<main>
  <section class="py-5 text-center container intro">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h2 class="fw-light">プログラミング学習者をつなぎチーム開発が経験できるプラットフォーム</h2>
        <p class="lead text-muted">プログラミングを独学していても、なかなか実務ではたらける力は身につかない。developeerはエンジニア同士をつなげ、チーム開発経験を積む場所を提供します。</p>
        <p>
          <a href="https://broadleaf-baroness-77d.notion.site/developeer-f35963e4bf764e5b93084d832af5a595" class="btn btn-primary my-2">developeerとは</a>
          {% if user.is_authenticated %}
          <a href="{% url 'app:projectlist' %}" class="btn btn-secondary my-2">開発プロジェクトをさがす</a>
          {% else %}
          <a href="{% url 'app:signup' %}" class="btn btn-secondary my-2">アカウントを作成</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="py-5 text-center container">
        <div class="row py-lg-5 bg-light">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h2 class="fw-light project-sample">チーム開発に参加しましょう</h2>
            <p>さまざまな技術スタックのチーム開発に無料で参加できます。もちろん自分で始めることも可能です。</p>
          </div>
        </div>
      </div>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 page-hide">
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="https://i.gyazo.com/88560b31776786816024bb109f592b9d.png" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">

            <div class="card-body">
              <p class="card-text">developeerを一緒に開発しませんか？</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="https://www.developeer.jp/project/5">
                    <button type="button" class="btn btn-primary">
                      詳しく見る
                     </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="https://i.gyazo.com/447576bd4b39a968a4e8cfc6c117697b.png" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">

            <div class="card-body">
              <p class="card-text">Rails×Next.jsでECサイトをチーム開発しよう</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="https://www.developeer.jp/project/8">
                    <button type="button" class="btn btn-primary">
                      詳しく見る
                     </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="https://i.gyazo.com/66a56be9f1b61bb878ac913705c9bed6.png" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">

            <div class="card-body">
              <p class="card-text">Vue.jsでカレンダーアプリをチーム開発しよう</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="https://www.developeer.jp/project/9">
                    <button type="button" class="btn btn-primary">
                      詳しく見る
                     </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row bg-light">
    <div class="py-5 text-center container">
      <div class="row py-lg-5 bg-light">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h2 class="fw-light">利用方法</h2>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <img class="rounded-circle" src="{% static 'images/idea.png' %}" alt="Generic placeholder image" width="140" height="140">
      <h3 class="circle-title">1. プロジェクト開始</h3>
      <p class="circle-text">自分がチーム開発したい技術を入力して、プロジェクトを開始しましょう。</p>
      <p><a class="circle-detail" href="https://broadleaf-baroness-77d.notion.site/d17b8422c91a415a969d4a5dc84a2d83">詳しく見る</a></p>
    </div>
    <div class="col-lg-4">
      <img class="rounded-circle" src="{% static 'images/project-match.png' %}" alt="Generic placeholder image" width="140" height="140">
      <h3 class="circle-title">2. マッチング</h3>
      <p class="circle-text">この開発に参加したい人とマッチングします。マッチングしたら、チャットをして開発内容を確認しましょう。</p>
      <p><a class="circle-detail" href="https://broadleaf-baroness-77d.notion.site/d17b8422c91a415a969d4a5dc84a2d83">詳しく見る</a></p>
    </div>
    <div class="col-lg-4">
      <img class="rounded-circle" src="{% static 'images/pc-programming.png' %}" alt="Generic placeholder image" width="140" height="140">
      <h3 class="circle-title">3. チーム開発</h3>
      <p class="circle-text">メンバーが集まったらチーム開発を始めることができます。独学ではできない、チーム開発を経験することで実装力を高めましょう。</p>
      <p><a class="circle-detail" href="https://broadleaf-baroness-77d.notion.site/d17b8422c91a415a969d4a5dc84a2d83">詳しく見る</a></p>
    </div>
    <div class="py-5 text-center container">
      <div class="row py-lg-5 bg-light intro-account">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h3 class="fw-light">developeerを使って、チーム開発を始めましょう</h3>
          {% if user.is_authenticated %}
          <p>
            <a href="{% url 'app:readyfor' %}" class="btn btn-primary my-2">チーム開発をはじめる</a>
          </p>
          {% else %}
          <p>
            <a href="{% url 'app:signup' %}" class="btn btn-primary my-2">アカウントを作成する</a>
          </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock main %}