app/urls.py
from django.urls import path
from .views.user import UserCreateView, ProfileUpdateView, LoginView, LogoutView, AccountView, AccountDeleteView, AccountPasswordView
from .views.course import CourseView, CourseDetailView
from .views.project import ProjectListView, ProjectDetailView, ProjectStartView, ProjectAdminView,  CreateCommentView, ProjectUpdateView, ProjectDeleteView, TopPageView

app_name = "app"

urlpatterns = [
    path('', TopPageView.as_view(), name='top'),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('course/', CourseView.as_view(), name='courselist'),
    path('course/<int:pk>', CourseDetailView.as_view(), name="course"),
    path('project/', ProjectListView.as_view(), name='projectlist'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name="project"),
    path('readyfor/', ProjectStartView.as_view(), name='readyfor'),
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountView.as_view(), name='account'),
    path('account/delete/<int:pk>', AccountDeleteView.as_view(), name='accountDelete'),
    path('account/password/<int:pk>', AccountPasswordView.as_view(), name='accountPassword'),
    path('project-dashboard/', ProjectAdminView.as_view(), name='projectadmin'),
    path('comment/', CreateCommentView.as_view(), name="comment"),
    path('project-dashboard/<int:pk>/edit', ProjectUpdateView.as_view(), name='projectEdit'),
    path('project-dashboard/<int:pk>/delete', ProjectDeleteView.as_view(), name='projectDelete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from common.error_log import server_error_display
import debug_toolbar

handler500 = server_error_display

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

app/views/course.py
from django.views.generic import ListView, DetailView
from ..models import Course

class CourseView(ListView):
    template_name = 'courses/course.html'
    model = Course

class CourseDetailView(DetailView):
    template_name = 'courses/courseDetail.html'
    model = Course

templates/courses/course.html
{% extends 'base.html' %}
{% block main %}
<main>
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">コース一覧</h1>
      <p class="lead text-muted">開発経験をつみたい言語・フレームワーク・ツールの教材を学習することができます。教材を学習してチーム開発に参加することが力になります。</p>
    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        {% for course in object_list %}
        <div class="card shadow-sm">
          <img src= "{{ course.img.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" >
            <div class="card-body">
            <p class="card-text">{{ course.title }}</p>
            <div class="btn-group" role="group" aria-label="Basic example">
              <a href="{% url 'app:course' course.pk %}">
                <button type="button" class="btn btn-primary">
                  詳しく見る
                </button>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
</main>
{% endblock main %}

templates/courses/courseDetail.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>Developeer - チーム開発のマッチングサービス</title>
    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/starter-template/">
    <!-- Bootstrap core CSS -->
    <link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/detail_page.css' %}">
    <link rel="shortcut icon" href="https://i.gyazo.com/bd55ec8e0518e1c2b21d514cb9ca6d76.jpg">
  </head>
<body>
  <div class="col-lg-8 mx-auto p-3 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
      <span class="fs-4">{{ course.title }}</span>
    </header>

    <main>
      <p class="fs-5 col-md-8">{{ course.description }}</p>
      <div class="mb-5">
        <a href="{{ course.content }}" class="btn btn-primary" target="_blank" rel="noopener noreferrer">学習する</a>
      </div>
      <hr class="col-3 col-md-2 mb-5">
      <a href="{% url 'app:courselist'%}" class="btn btn-secondary btn-sm">コース一覧へ</a>
    </main>

    <footer class="pt-5 my-5 text-muted border-top">
      Created by the developeer team &middot; &copy; 2022
    </footer>
  </div>
</body>
</html>